Controllers/ActorsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using movies_ecommerce.Models;
using movies_ecommerce.Services;
using movies_ecommerce.ViewModel;

namespace movies_ecommerce.Controllers
{
   // [Authorize(Roles ="Admin,Actor")]//Actor
    public class ActorsController : Controller
    {
        private readonly IActorsService _actorsService;
        public ActorsController(IActorsService actorsService)
        {
            _actorsService = actorsService;
        }
        public IActionResult Index()
        {
            var The_Actors = _actorsService.GetAll();
            return View(The_Actors);
        }
        public IActionResult Search(string term)
        {
            var search =_actorsService.Search(term);
            return View(nameof(Index), search);
        }
        [HttpGet]
        public IActionResult AddActor()
        {
            AddActorViewModel model = new AddActorViewModel();
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddActor(AddActorViewModel model) 
        {
            if (!ModelState.IsValid)
            {
                AddActorViewModel moodel = new AddActorViewModel();
                return View(moodel);
            }
            await _actorsService.AddActor(model);
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var actor = _actorsService.GetById(id);
            if(actor == null) 
                return NotFound();
            EditActorViewModel model = new()
            {
                Id = id,
                Name = actor.Name,
                Bio = actor.Bio,
                CuruntCover = actor.Cover
            };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditActorViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var actor= await _actorsService.Edit(model);
            if (actor == null)
                return BadRequest();
            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles ="Admin")]
        public IActionResult Delete(int id)
        {
            var isDelete = _actorsService.Delete(id);
            return isDelete ? Ok() : BadRequest();
        }
    }
}

Controllers/CinemasController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using movies_ecommerce.Services;
using movies_ecommerce.ViewModel;

namespace movies_ecommerce.Controllers
{
   // [Authorize(Roles ="Admin,Manager")]
    public class CinemasController : Controller
    {
        private readonly ICinemasService _cinemasService;
        public CinemasController(ICinemasService cinemasService)
        {
            _cinemasService = cinemasService;
        }
        public IActionResult Index()
        {
            var AllSinemas = _cinemasService.GetAll();
            return View(AllSinemas);
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(AddActorViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
             await _cinemasService.Add(model);

            return RedirectToAction(nameof(Index));
        }
        //             _actianService.add(modelView);
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var c = _cinemasService.getByid(id);
            if (c == null)
                return NotFound();
            EditActorViewModel model = new EditActorViewModel();
            model.Id = id;
            model.Name = c.Name;
            model.CuruntCover = c.Logo;
            model.Bio = c.Description;

            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditActorViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var cinema = await _cinemasService.Edit(model);
            if(cinema == null)
                return BadRequest();

            return RedirectToAction(nameof(Index));
        }
        public IActionResult Search(string term)
        {
            var search = _cinemasService.Search(term);
            return View(nameof(Index), search);
        }
        public IActionResult Delete(int id)
        {
            var isdleted= _cinemasService.Delete(id);
            return isdleted? Ok() : BadRequest();
        }
    }
}

Controllers/MoviesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using movies_ecommerce.Models;
using movies_ecommerce.Services;

namespace movies_ecommerce.Controllers
{
    [Authorize(Roles ="Admin")]
    public class MoviesController : Controller
    {
        private readonly IActorsService _actorsService;
        private readonly IProducersService _producersService;
        private readonly ICinemasService _cinemasService;
        private readonly IMoviesServices _moviesServices;
        private readonly ICategoriesService _categoriesService;
        public MoviesController(IActorsService actorsService,
            ICinemasService cinemasService, IProducersService producersService,
            IMoviesServices moviesServices, ICategoriesService categoriesService)
        {
            _actorsService = actorsService;
            _producersService = producersService;
            _moviesServices = moviesServices;
            _cinemasService = cinemasService;
            _categoriesService = categoriesService;
        }
        public IActionResult Index()
        {
            var model = _moviesServices.GetAll();
            return View(model);
        }
        [HttpGet]
        public IActionResult Add()
        {
            MovieViewModel model = new()
            {
                Producers = _producersService.GetProducers(),
                Categories = _categoriesService.GetCategories(),
                Actors = _actorsService.GetActors(),
                Cinemas = _cinemasService.GetCinemas(),

            };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(MovieViewModel model)
        {
            if (!ModelState.IsValid)
            {
                MovieViewModel Moviemodel = new MovieViewModel();
                model.Producers = _producersService.GetProducers();
                model.Categories = _categoriesService.GetCategories();
                model.Actors = _actorsService.GetActors();
                model.Cinemas = _cinemasService.GetCinemas();
                return View(Moviemodel);
            }
            await _moviesServices.Add(model);
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var M = _moviesServices.GetById(id);
            if (M == null)
                return NotFound();
            EditMovieViewModel model = new EditMovieViewModel();
            model.id = id;
            model.DeScription = M.Description;
            model.Name = M.Name;
            model.price = M.Price;
            model.CurrentCover = M.Cover;
            model.StartDate = M.StartDate;
            model.EndDate = M.EndDate;
            model.CategoryId = M.CategoryId;
            model.CinemaId = M.CinemaId;
            model.ProducerId = M.ProducerId;
            model.SelectActors = M.actors_Movies.Select(x => x.ActorId).ToList();
            model.Cinemas = _cinemasService.GetCinemas().ToList();
            model.Categories = _categoriesService.GetCategories().ToList();
            model.Actors = _actorsService.GetActors().ToList();
            model.Producers = _producersService.GetProducers().ToList();
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditMovieViewModel MV)
        {
            if (!ModelState.IsValid)
            {
                EditMovieViewModel model = new();
                model.Cinemas = _cinemasService.GetCinemas().ToList();
                model.Categories = _categoriesService.GetCategories().ToList();
                model.Actors = _actorsService.GetActors().ToList();
                model.Producers = _producersService.GetProducers().ToList();
                return View(model);
            }
            var returnmovie = await _moviesServices.Edit(MV);
            if (returnmovie == null)
                return BadRequest();
            return RedirectToAction(nameof(Index));
        }
         public IActionResult Delete(int id)
        {
            bool movie = _moviesServices.Delete(id);
            

            return movie ? Ok() : BadRequest();

        }
        public IActionResult Search(string term)
        {
            var search = _moviesServices.Search(term);
            return View(nameof(Index), search);
        }
    }
}

Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace movies_ecommerce.Controllers
{
    [Authorize(Roles ="Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult NewRole() 
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> NewRole(RoleViewModel Role)
        {
            if(ModelState.IsValid)
            {
               
                IdentityRole r = new IdentityRole();
                r.Name = Role.RoleName;
                IdentityResult result = await _roleManager.CreateAsync(r);
                if(result.Succeeded)
                {
                    return RedirectToAction("index");
                }
                else
                {
                    foreach(var i in result.Errors)
                    {
                        ModelState.AddModelError("", " Error in something ");
                    }
                }
            }
            return View(Role);
        }
    }
}

Views/Shared/AddPartialView.cshtml
@model AddActorViewModel
<div class="row">
    <div class="col-md-6">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="control-label mt-2"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Bio" class="control-label mt-2"></label>
            <input asp-for="Bio" class="form-control" />
            <span asp-validation-for="Bio" class="text-danger"></span>
        </div>
        <partial name="CoverPartialView" />
        <div class="form-group mt-3">
            <input type="submit" value="AddNew" class="btn btn-primary AddNew" />
        </div>
    </div>
    <div class="col-md-6 d-flex justify-content-end">
        <img class="cover-preview d-none " alt="Cover" style="width:300px;height:300px" />
    </div>
</div>

Views/Shared/CoverPartialView.cshtml
@model AddActorViewModel
<div class="form-group">
    <label asp-for="Cover" class="form-label mt-4"></label>
    <input asp-for="Cover" class="form-control" type="file"
           data-rule-extension="@FileSettings.AllowedExtentions.Replace("." , string.Empty)"
           data-msg-extension="not allowed extensionssssssssss"
           data-rule-filesize="@FileSettings.MaxSizeinByte"
           data-msg-filesize="maximum allowed size is @FileSettings.MaxSizeInMB MB" />
    <span asp-validation-for="Cover" class="text-danger"></span>
</div>

Views/Shared/EditPartialView.cshtml
@model EditActorViewModel

    <div class="col-md-6">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="control-label mt-2"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Bio" class="control-label mt-2"></label>
            <input asp-for="Bio" class="form-control" />
            <span asp-validation-for="Bio" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Cover" class="form-label mt-4"></label>
            <input asp-for="Cover" class="form-control" type="file"
                   data-rule-extension="@FileSettings.AllowedExtentions.Replace("." , string.Empty)"
                   data-msg-extension="not allowed extensionssssssssss"
                   data-rule-filesize="@FileSettings.MaxSizeinByte"
                   data-msg-filesize="maximum allowed size is @FileSettings.MaxSizeInMB MB" />
            <span asp-validation-for="Cover" class="text-danger"></span>
        </div>
        <div class="form-group mt-3">
            <input type="submit" value="Update" class="btn btn-primary" />
        </div>
    </div>

Views/Shared/NameanddeletePartialview.cshtml
<td class="align-content-center">@Model.Name</td>
<td>
    <div class="d-flex justify-content-end">
        @model BasicEntity0
        <a class="btn btn-info rounded rounded-3 me-2" asp-action="Edit" asp-route-id="@Model.Id">
            <i class="bi bi-pencil-square "></i>
        </a>

        <a onclick="if(!confirm('are you sure u want to delete it !?')){return false}"
           class="btn btn-danger rounded rounded-0 " asp-action="Delete" asp-route-id="@Model.Id">
            <i class="bi bi-trash3 "></i>
        </a>
    </div>
</td>

Views/Shared/SearchPartialView.cshtml
<div class="row mb-2">
    <div class="col-9">
    </div>
    <div class="col-3">
        <form class="form-inline" asp-action="search">
            <div class="d-flex">
                <input type="search" name="term" placeholder="Search" class="form-control mr-sm-2">
                <button class="btn btn-outline-success my-2 my-sm-0">Search</button>
            </div>
        </form>
    </div>
</div>

Views/Shared/_ActionPartialView.cshtml
@model int
<div class="d-flex justify-content-end">
    <a class="btn btn-info rounded rounded-3 me-2" asp-action="Edit" asp-route-id="@Model">
        <i class="bi bi-pencil-square "></i>
    </a>

    <a onclick="if(!confirm('are you sure u want to delete it !?')){return false}" class="btn btn-danger rounded rounded-0 " asp-action="Delete" asp-route-id="@Model">
        <i class="bi bi-trash3 "></i>
    </a>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ecommerce-@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootstrap.min (2).css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/css/cinima.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/movies_ecommerce.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary mb-3" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">movies_ecommerce</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
               
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity!.IsAuthenticated)
                        {
                           @*  @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                            } *@
                            @if (User.IsInRole("Actor"))
                            {
                                <li class="nav-item cinema">
                                    <a class="nav-link text-dark" asp-controller="Actors" asp-action="Index">Actors</a>
                                </li>
                            }
                            @if (User.IsInRole("Producer"))
                            {
                                <li class="nav-item cinema">
                                    <a class="nav-link text-dark" asp-controller="Producers" asp-action="Index">producers</a>
                                </li>

                            }
                            @if (User.IsInRole("Manager"))
                            {
                                <li class="nav-item cinema">
                                    <a class="nav-link text-dark" asp-controller="Cinemas" asp-action="Index">Cinemas</a>
                                </li>
                            }

                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item cinema">
                                    <a class="nav-link text-dark" asp-controller="Cinemas" asp-action="Index">Cinemas</a>
                                </li>
                                <li class="nav-item cinema">
                                    <a class="nav-link text-dark" asp-controller="Actors" asp-action="Index">Actors</a>
                                </li>
                                <li class="nav-item cinema">
                                    <a class="nav-link text-dark" asp-controller="Producers" asp-action="Index">producers</a>
                                </li>
                                <li class="nav-item cinema">
                                    <a class="nav-link text-dark" asp-controller="Movies" asp-action="Index">Movies</a>
                                </li>

                                <li class="nav-item cinema">
                                    <a class="nav-link text-dark" asp-controller="Role" asp-action="NewRole">NewRole </a>
                                </li>
                                <li class="nav-item cinema">
                                    <a class="nav-link text-dark" asp-controller="Account" asp-action="Register">Add User</a>
                                </li>
                            }
                        }

                    </ul>
                    <ul class="navbar-nav ">
                       
                       
                        @if (User.Identity.IsAuthenticated == true)
                        {
                            <li class="nav-item" >
                                <a class="nav-link text-dark" href="#"><b style="color:white">Welcome @User.Identity.Name </b></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                    </div>
                
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - movies_ecommerce - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_SectionPartialView.cshtml
<partial name="_ValidationScriptsPartial" />
<script src="~/js/cover-preview.js" asp-append-version="true"></script>
<script src="~/js/filesize-validation.js" asp-append-version="true"></script>